project:
  type: website

website:
  title: "Dr. Silvia-Jessica Mostacedo-Marasovic"
    site-description: "DBER researcher at UTA studying water literacy, sustainability education, and decision-making using learning analytics and game theory."
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: service.qmd
        text: Service

format:
  html:
    theme: cosmo
    toc: false
