project:
  type: website

website:
  title: "Silvia-Jessica Mostacedo-Marasovic"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: service.qmd
        text: Service

format:
  html:
    theme: cosmo
    toc: false
